import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";

// next.js typescript example: https://github.com/vercel/next.js/tree/canary/examples/with-typescript

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{`YiDao's Blog`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* eslint-disable-next-line react/no-unescaped-entities */}
      <div>Hi I'm Xiao, a front-end developer.</div>
    </div>
  );
};

export default Home;
