import { getSortedPosts } from "@/lib/getPosts";
import { IBlogPost } from "@/types/type";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import styles from "../styles/Home.module.css";

type Props = {
  allPostsData: IBlogPost[];
};

// next.js typescript example: https://github.com/vercel/next.js/tree/canary/examples/with-typescript

const Home: NextPage<Props> = ({ allPostsData }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{`YiDao's Blog`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        {allPostsData.map((post: IBlogPost) => (
          <li key={post.slug} className="mb-4">
            <Link href={`/posts/${post.slug}`}>{post.title}</Link>
            <div>{post.date}</div>
            <div>{post.slug}</div>
          </li>
        ))}
      </ul>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const allPostsData = getSortedPosts();
  return {
    props: {
      allPostsData,
    },
  };
};

export default Home;
